name: 🏗️ BUILD ANDROID14-6.1

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    env:
      LLVM: 1
      LLVM_IAS: 1
      LD: ld.lld
      CC: clang
      CLANG_TRIPLE: aarch64-linux-gnu-
      CROSS_COMPILE: aarch64-linux-gnu-
      CROSS_COMPILE_COMPAT: arm-linux-gnueabi-
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Setup Environment
      run: |
        sudo apt update
        sudo apt install -y git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler rename libelf-dev dwarves libncurses-dev clang lld llvm

    - name: Read Configuration
      run: |
        CONFIG_ENV=config.properties.gki_1461
        echo "KERNEL_SOURCE=$(cat $CONFIG_ENV | grep -w "KERNEL_SOURCE" | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "KERNEL_CONFIG=$(cat $CONFIG_ENV | grep -w "KERNEL_CONFIG" | cut -d "=" -f 2)" >> $GITHUB_ENV
        echo "DISABLE_LTO=$(cat $CONFIG_ENV | grep -w "DISABLE-LTO" | cut -d "=" -f 2)" >> $GITHUB_ENV

    - name: Download Kernel Source
      run: |
        mkdir -p kernel_workspace
        cd kernel_workspace
        git clone ${{ env.KERNEL_SOURCE }} -b main android-kernel --depth=1

    - name: Build Kernel
      run: |
        cd kernel_workspace/android-kernel
        
        # 1. Generate .config pertama kali
        make O=out ARCH=arm64 ${{ env.KERNEL_CONFIG }}
        
        # 2. FORCE PATCH: Edit file .config yang sudah jadi (ini tidak akan ditimpa)
        # Fix VA_BITS
        sed -i 's/CONFIG_ARM64_VA_BITS=[0-9]*/CONFIG_ARM64_VA_BITS=39/g' out/.config
        # Fix LTO jika DISABLE-LTO=true
        if [ "${{ env.DISABLE_LTO }}" = "true" ]; then
            sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/' out/.config || echo "CONFIG_LTO=n" >> out/.config
            echo "CONFIG_LTO_NONE=y" >> out/.config
        fi
        
        # 3. Kompilasi (Pastikan pakai O=out)
        make -j$(nproc --all) O=out ARCH=arm64 CC=clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu-

    - name: Upload Kernel
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-Output
        path: kernel_workspace/android-kernel/out/arch/arm64/boot/Image*
        
